{
    'name': 'GxP Spreadsheet Control',
    'version': '12.0.1.0.0',
    'summary': 'Controlled spreadsheet lifecycle with e-signature and audit trail',
    'category': 'Quality',
    'author': 'GxP',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'data/catalog_data.xml',
        'views/controlled_sheet_views.xml',
        'views/sheet_version_views.xml',
        'views/validation_views.xml',
        'views/change_control_views.xml',
        'views/review_views.xml',
        'views/audit_views.xml',
        'views/assets.xml',
        'views/catalog_views.xml',
        'wizard/sign_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
}
